{
  "uid" : "d1cd30f29a8c53b0",
  "name" : "rename column in sync",
  "fullName" : "test_pipeline.TestPipeline#test_rename_sync",
  "historyId" : "4e70ff02fc8f0e6b5867676cc9ee7a1d",
  "time" : {
    "start" : 1660203495229,
    "stop" : 1660203495864,
    "duration" : 635
  },
  "status" : "broken",
  "statusMessage" : "IndexError: tuple index out of range",
  "statusTrace" : "self = <lib.cli.Job object at 0x7fa831b6eb50>\n\n    def start(self):\n        try:\n>           status = self.status()\n\n../lib/cli.py:2504: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <lib.cli.Job object at 0x7fa831b6eb50>, res = None, quiet = True\n\n    def status(self, res=None, quiet=True):\n        if res is None:\n>           res = req.get(\"/Task/\" + self.id).json()\nE           TypeError: can only concatenate str (not \"NoneType\") to str\n\n../lib/cli.py:2531: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test.test_pipeline.TestPipeline object at 0x7fa82d0c8e90>\n\n    @allure.title(\"rename column in sync\")\n    def test_rename_sync(self):\n        ori_name = f\"rename_sync_{random_str()}\"\n        new_name = f\"rename_sync_{random_str()}\"\n        p = make_new_pipeline(ori_name)\n        p1 = p.readFrom(source_name)\n        p1.dag.jobType = JobType.sync\n        p2 = p1.rename(ori_name, new_name).writeTo(sink_name)\n        assert id(p1) != id(p2)\n>       p2.start()\n\ntest_pipeline.py:133: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../lib/cli.py:112: in func_wrapper\n    return obj(*args, **kargs)\n../lib/cli.py:1936: in start\n    if job.start():\n../lib/cli.py:2508: in start\n    logger.info(\"job {} save failed.\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <lib.log.Logger object at 0x7fa82e6f5a10>\nargs = ('job {} save failed.',), kargs = {}\nmsg = 'job \\x1b[1;32m{}\\x1b[0m save failed.'\n\n    def info(self, *args, **kargs):\n        msg = args[0].replace(\"{}\", \"\\033[1;32m{}\\033[0m\")\n>       self._print(msg.format(*args[1:]), **kargs)\nE       IndexError: tuple index out of range\n\n../lib/log.py:64: IndexError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "pipeline"
  }, {
    "name" : "suite",
    "value" : "test_pipeline"
  }, {
    "name" : "subSuite",
    "value" : "TestPipeline"
  }, {
    "name" : "host",
    "value" : "cf856c84ccb1"
  }, {
    "name" : "thread",
    "value" : "863-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_pipeline"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 5,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 5
      },
      "items" : [ {
        "uid" : "7ee0f3b06b757338",
        "status" : "broken",
        "statusDetails" : "IndexError: tuple index out of range",
        "time" : {
          "start" : 1660192590239,
          "stop" : 1660192590644,
          "duration" : 405
        }
      }, {
        "uid" : "590373741b4cdbc5",
        "status" : "broken",
        "statusDetails" : "IndexError: tuple index out of range",
        "time" : {
          "start" : 1660188063737,
          "stop" : 1660188064038,
          "duration" : 301
        }
      }, {
        "uid" : "5e0cbd650c262697",
        "status" : "broken",
        "statusDetails" : "IndexError: tuple index out of range",
        "time" : {
          "start" : 1660131358564,
          "stop" : 1660131359073,
          "duration" : 509
        }
      }, {
        "uid" : "873f86f041a5385f",
        "status" : "broken",
        "statusDetails" : "IndexError: tuple index out of range",
        "time" : {
          "start" : 1660126810046,
          "stop" : 1660126810359,
          "duration" : 313
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "d1cd30f29a8c53b0.json",
  "parameterValues" : [ ]
}